name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Installing Node Modules
        run: yarn

      - name: Running linting checks
        run: |
          yarn check-types
          yarn check-lint
          yarn check-format
